import type { BotDoc } from "@/lib/firestore";

/** Shown when Firestore is empty or unavailable (dev / marketing). */
export const FALLBACK_BOTS: BotDoc[] = [
  {
    id: "xauusd-grid",
    name: "XAUUSD Grid",
    subtitle: "Gold Grid System",
    asset: "XAUUSD",
    assetTag: "Gold",
    status: "live",
    risk: "Medium",
    gain: "+247.3%",
    drawdown: "12.4%",
    winRate: "73.2%",
    trades: "847",
    description:
      "Grid-based strategy on Gold with dynamic lot sizing. Profits from price oscillations within defined ranges.",
    pairs: ["XAUUSD"],
    minDeposit: "$500",
    imageKey: "",
    storageFolder: "xauusd-grid",
    fileKey: "bots/xauusd-grid/ea-mt5.ex5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "forex-scalper",
    name: "Forex Scalper",
    subtitle: "Major Pairs Scalper",
    asset: "EURUSD · GBPUSD",
    assetTag: "Majors",
    status: "live",
    risk: "Low",
    gain: "+158.9%",
    drawdown: "8.7%",
    winRate: "68.5%",
    trades: "1,342",
    description:
      "High-frequency scalping on major forex pairs during London and New York sessions.",
    pairs: ["EURUSD", "GBPUSD", "USDJPY"],
    minDeposit: "$300",
    imageKey: "",
    storageFolder: "forex-scalper",
    fileKey: "bots/forex-scalper/ea-mt5.ex5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "multi-asset",
    name: "Multi-Asset",
    subtitle: "Diversified Portfolio",
    asset: "Gold · Forex · CFDs",
    assetTag: "Portfolio",
    status: "live",
    risk: "High",
    gain: "+312.6%",
    drawdown: "15.1%",
    winRate: "71.8%",
    trades: "623",
    description:
      "Runs all strategy modules across correlated and uncorrelated instruments with portfolio-level drawdown controls.",
    pairs: ["XAUUSD", "EURUSD", "NASDAQ", "BTCUSD"],
    minDeposit: "$1,000",
    imageKey: "",
    storageFolder: "multi-asset",
    fileKey: "bots/multi-asset/ea-mt5.ex5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "index-momentum",
    name: "Index Momentum",
    subtitle: "US & EU Indices",
    asset: "NASDAQ · SP500",
    assetTag: "Indices",
    status: "beta",
    risk: "Medium",
    gain: "+94.1%",
    drawdown: "11.2%",
    winRate: "65.4%",
    trades: "312",
    description:
      "Trend-following on equity indices with momentum signals and session-based filters.",
    pairs: ["NAS100", "SPX500", "GER40"],
    minDeposit: "$500",
    imageKey: "",
    storageFolder: "index-momentum",
    fileKey: "bots/index-momentum/ea-mt5.ex5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "crypto-cfd",
    name: "Crypto CFD",
    subtitle: "Digital Asset Strategy",
    asset: "BTC · ETH · SOL",
    assetTag: "Crypto",
    status: "soon",
    risk: "High",
    gain: "—",
    drawdown: "—",
    winRate: "—",
    trades: "—",
    description:
      "Volatility-adaptive strategy for crypto CFDs with momentum and mean-reversion techniques.",
    pairs: ["BTCUSD", "ETHUSD", "SOLUSD"],
    minDeposit: "$500",
    imageKey: "",
    fileKey: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "news-event",
    name: "News Event",
    subtitle: "High-Impact Releases",
    asset: "Multi-Asset",
    assetTag: "Event-Driven",
    status: "soon",
    risk: "High",
    gain: "—",
    drawdown: "—",
    winRate: "—",
    trades: "—",
    description:
      "Positions ahead of high-impact economic releases with rapid entry and trailing exits.",
    pairs: ["EURUSD", "XAUUSD", "USDJPY"],
    minDeposit: "$1,000",
    imageKey: "",
    fileKey: "",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export function getFallbackBot(id: string): BotDoc | null {
  return FALLBACK_BOTS.find((b) => b.id === id) ?? null;
}
