#ifndef MQL_AUTO_FORWARDS_INCLUDED_F580F8B7182A490A
#define MQL_AUTO_FORWARDS_INCLUDED_F580F8B7182A490A
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5

#line 21 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotParseValid(const string body);
#line 28 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotParseJsonString(const string body, const string field);
#line 44 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotFriendlyError(const string apiCode, const string apiMessage, const string terminalAccount, const string licensedAccount);
#line 75 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void QauntraBotShowLicenseError(const string title, const string detail);
#line 81 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotHttpGet(const string url, string &response, string &err);
#line 104 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotVerifyLicense(const string licenseKey, const string apiBaseUrl, string &errorMessage, const int recheckSeconds);
#line 166 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotJsonEscape(string s);
#line 174 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotChartTimeframe();
#line 209 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotBuildBotStatusJson();
#line 277 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotPushTradingStats(const string licenseKey, const string botStatusJson);
#line 319 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotAutoSyncBalance(const string licenseKey, const bool forceNow);
#line 445 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
define DASH_C3 325 string Pad(string s, int w);
#line 450 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string Trunc(string s, int n);
#line 456 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
string DayName(int dow);
#line 471 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void RefreshDayStartEquity();
#line 482 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
double GetFloatingPnlUsd();
#line 496 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void RefreshEmaCache();
#line 518 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void DashLabel(string id, int x, int y, string txt, color clr, int sz);
#line 539 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void CreateDashboard();
#line 558 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void DeleteDashboard();
#line 567 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateDashboard();
#line 828 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool IsNearMarketClose();
#line 839 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool IsFridayShutdownActive(string &reason);
#line 856 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool IsProfitStopActive(string &reason);
#line 874 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool VerifyQauntraBotLicense(string &err);
#line 1266 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
bool LevelAlreadyOpen(ENUM_POSITION_TYPE side, double triggerPrice);
#line 1282 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
double GetGridLot(int level);
#line 1289 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateSideTPs(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1316 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateSideSL(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1348 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
double GetSideProfit(ENUM_POSITION_TYPE side);
#line 1364 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void CloseSide(ENUM_POSITION_TYPE side);
#line 1384 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
void CloseAllPositions();
#line 1406 "/Users/bunkheangheng/Desktop/Project/QauntraBot/.next/standalone/examples/EaSample/SuperFiveCentBot.mq5"
double NormalizeLot(double lots);

#endif
