#ifndef MQL_AUTO_FORWARDS_INCLUDED_D4A9592F7A3B62E4
#define MQL_AUTO_FORWARDS_INCLUDED_D4A9592F7A3B62E4
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5

#line 22 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotParseValid(const string body);
#line 29 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotParseJsonString(const string body, const string field);
#line 45 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotFriendlyError(const string apiCode, const string apiMessage, const string terminalAccount, const string licensedAccount);
#line 76 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void QauntraBotShowLicenseError(const string title, const string detail);
#line 82 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotHttpGet(const string url, string &response, string &err);
#line 105 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotVerifyLicense(const string licenseKey, const string apiBaseUrl, string &errorMessage, const int recheckSeconds);
#line 165 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotJsonEscape(string s);
#line 173 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotChartTimeframe();
#line 208 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotBuildBotStatusJson();
#line 276 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotPushTradingStats(const string licenseKey, const string botStatusJson);
#line 331 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotAutoSyncBalance(const string licenseKey, const bool forceNow);
#line 444 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
define DASH_C3 325 string Pad(string s, int w);
#line 449 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string Trunc(string s, int n);
#line 455 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string DayName(int dow);
#line 470 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void RefreshDayStartEquity();
#line 481 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetFloatingPnlUsd();
#line 495 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void RefreshEmaCache();
#line 517 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void DashLabel(string id, int x, int y, string txt, color clr, int sz);
#line 538 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CreateDashboard();
#line 557 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void DeleteDashboard();
#line 566 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateDashboard();
#line 827 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool IsProfitStopActive(string &reason);
#line 845 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool VerifyQauntraBotLicense(string &err);
#line 1224 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool LevelAlreadyOpen(ENUM_POSITION_TYPE side, double triggerPrice);
#line 1240 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetGridLot(int level);
#line 1247 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateSideTPs(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1274 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateSideSL(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1306 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetSideProfit(ENUM_POSITION_TYPE side);
#line 1322 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CloseSide(ENUM_POSITION_TYPE side);
#line 1342 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CloseAllPositions();
#line 1364 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double NormalizeLot(double lots);

#endif
