#ifndef MQL_AUTO_FORWARDS_INCLUDED_E71E9FD6FDE96BC6
#define MQL_AUTO_FORWARDS_INCLUDED_E71E9FD6FDE96BC6
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5

#line 22 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotParseValid(const string body);
#line 29 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotParseJsonString(const string body, const string field);
#line 45 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotFriendlyError(const string apiCode, const string apiMessage, const string terminalAccount, const string licensedAccount);
#line 76 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void QauntraBotShowLicenseError(const string title, const string detail);
#line 82 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotHttpGet(const string url, string &response, string &err);
#line 105 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotVerifyLicense(const string licenseKey, const string apiBaseUrl, string &errorMessage, const int recheckSeconds);
#line 167 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotJsonEscape(string s);
#line 175 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotChartTimeframe();
#line 210 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string QauntraBotBuildBotStatusJson();
#line 278 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotPushTradingStats(const string licenseKey, const string botStatusJson);
#line 333 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool QauntraBotAutoSyncBalance(const string licenseKey, const bool forceNow);
#line 459 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
define DASH_C3 325 string Pad(string s, int w);
#line 464 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string Trunc(string s, int n);
#line 470 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
string DayName(int dow);
#line 485 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void RefreshDayStartEquity();
#line 496 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
double GetFloatingPnlUsd();
#line 510 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void RefreshEmaCache();
#line 532 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void DashLabel(string id, int x, int y, string txt, color clr, int sz);
#line 553 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void CreateDashboard();
#line 572 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void DeleteDashboard();
#line 581 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateDashboard();
#line 842 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool IsNearMarketClose();
#line 853 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool IsFridayShutdownActive(string &reason);
#line 870 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool IsProfitStopActive(string &reason);
#line 888 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool VerifyQauntraBotLicense(string &err);
#line 1285 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
bool LevelAlreadyOpen(ENUM_POSITION_TYPE side, double triggerPrice);
#line 1301 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
double GetGridLot(int level);
#line 1308 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateSideTPs(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1335 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void UpdateSideSL(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1367 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
double GetSideProfit(ENUM_POSITION_TYPE side);
#line 1383 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void CloseSide(ENUM_POSITION_TYPE side);
#line 1403 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
void CloseAllPositions();
#line 1425 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBot.mq5"
double NormalizeLot(double lots);

#endif
