#ifndef MQL_AUTO_FORWARDS_INCLUDED_D4A9592F7A3B62E4
#define MQL_AUTO_FORWARDS_INCLUDED_D4A9592F7A3B62E4
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5

#line 21 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotParseValid(const string body);
#line 28 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotParseJsonString(const string body, const string field);
#line 44 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotFriendlyError(const string apiCode, const string apiMessage, const string terminalAccount, const string licensedAccount);
#line 75 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void QauntraBotShowLicenseError(const string title, const string detail);
#line 81 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotHttpGet(const string url, string &response, string &err);
#line 104 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotVerifyLicense(const string licenseKey, const string apiBaseUrl, string &errorMessage, const int recheckSeconds);
#line 164 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotJsonEscape(string s);
#line 172 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotChartTimeframe();
#line 207 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string QauntraBotBuildBotStatusJson();
#line 275 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotPushTradingStats(const string licenseKey, const string botStatusJson);
#line 317 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool QauntraBotAutoSyncBalance(const string licenseKey, const bool forceNow);
#line 430 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
define DASH_C3 325 string Pad(string s, int w);
#line 435 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string Trunc(string s, int n);
#line 441 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
string DayName(int dow);
#line 456 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void RefreshDayStartEquity();
#line 467 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetFloatingPnlUsd();
#line 481 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void RefreshEmaCache();
#line 503 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void DashLabel(string id, int x, int y, string txt, color clr, int sz);
#line 524 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CreateDashboard();
#line 543 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void DeleteDashboard();
#line 552 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateDashboard();
#line 813 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool IsProfitStopActive(string &reason);
#line 831 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool VerifyQauntraBotLicense(string &err);
#line 1205 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
bool LevelAlreadyOpen(ENUM_POSITION_TYPE side, double triggerPrice);
#line 1221 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetGridLot(int level);
#line 1228 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateSideTPs(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1255 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void UpdateSideSL(ENUM_POSITION_TYPE side, double lots, double avg);
#line 1287 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double GetSideProfit(ENUM_POSITION_TYPE side);
#line 1303 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CloseSide(ENUM_POSITION_TYPE side);
#line 1323 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
void CloseAllPositions();
#line 1345 "/Users/bunkheangheng/Desktop/Project/QauntraBot/examples/EaSample/SuperFiveCentBotBTC.mq5"
double NormalizeLot(double lots);

#endif
